name: soundhoard - Test

on:
  push:
    paths:
      - "soundhoard/**"
      - ".github/workflows/soundhoard-test.yml"

defaults:
  run:
    working-directory: soundhoard

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true

      - run: uv python install

      - run: uv sync --dev

      - name: Check formatting and linting
        run: make check-format

      - name: Type check
        run: make typecheck

      - name: Test with pytest
        run: make test
